#!/bin/sh

DNSCONTROL_VERSION=v3.3.0

curl \
  --output dnscontrol \
  --location \
  https://github.com/StackExchange/dnscontrol/releases/download/$DNSCONTROL_VERSION/dnscontrol-Linux

chmod +x dnscontrol
